INSERT INTO allergen(name) VALUES
 ('Millet')
,('Oat Milk')
,('Cod')
,('Quinoa')
,('Eggplant')
,('Soybeans')
,('Mustard Seeds')
,('Parsley')
,('Almond Milk')
,('Corn Starch')
,('Corn Flour')
,('Sunset Yellow')
,('Gelatin')
,('Lychee')
,('Brazil Nuts')
,('Psyllium Husk')
,('Pecans')
,('Allura Red')
,('Lamb')
,('Buckwheat')
,('Tilapia')
,('Hemp Milk')
,('Sunflower Seeds')
,('Sodium Nitrate')
,('Natto')
,('Xanthan Gum')
,('Passion Fruit')
,('Hominy')
,('Tamari')
,('Cumin')
,('Amaranth')
,('Saccharin')
,('Mint')
,('Soy Lecithin')
,('Sodium Nitrite')
,('Tragacanth Gum')
,('Duck')
,('Pea Shoots')
,('Acacia Gum')
,('Tartrazine')
,('Lobster')
,('Anise')
,('Navy Beans')
,('Basil')
,('Sage')
,('Annatto')
,('Split Peas')
,('Nutritional Yeast')
,('Poppy Seeds')
,('Coriander')
,('Pistachios')
,('Chives')
,('Halibut')
,('Miso Paste')
,('Chickpeas')
,('Carmine')
,('Onions')
,('Acesulfame Potassium')
,('Green Peas')
,('Kamut')
,('Millet Flour')
,('Carob Bean Gum')
,('Royal Jelly')
,('Stevia')
,('Barley')
,('Soy Sauce')
,('Pea Protein')
,('Potatoes')
,('Teff')
,('Thyme')
,('Hydrolyzed Vegetable Protein (HVP)')
,('Grits')
,('Chestnuts')
,('Anchovies')
,('Sucralose')
,('Scallops')
,('Chia Seeds')
,('Bananas')
,('Venison')
,('Disodium Inosinate')
,('Seitan')
,('Peanuts')
,('Dragon Fruit')
,('Salmon')
,('Papaya')
,('Sesame Seeds')
,('Nutmeg')
,('Erythrosine')
,('Cream')
,('Tuna')
,('Hemp Seeds')
,('Fish')
,('Dill')
,('Polenta')
,('Star Fruit')
,('Shallots')
,('Haddock')
,('Beef')
,('Almonds')
,('Crab');
