INSERT INTO cousines(type) VALUES
 ('Gluten-Free')
,('Swiss')
,('Fusion')
,('Korean')
,('Filipino')
,('BBQ')
,('Bakery')
,('German')
,('Soul Food')
,('Tibetan')
,('Middle Eastern')
,('Peruvian')
,('Sri Lankan')
,('Deli')
,('Bistro')
,('Dutch')
,('Tex-Mex')
,('Mexican')
,('Moroccan')
,('Farm-to-Table')
,('Bulgarian')
,('Armenian')
,('Swedish')
,('Keto')
,('Tea House')
,('Street Food')
,('Smoothie Bar')
,('Serbian')
,('Brazilian')
,('Vegetarian')
,('Healthy')
,('Pakistani')
,('Coffee Shop')
,('Croatian')
,('Kazakh')
,('American')
,('Ethiopian')
,('Malaysian')
,('Slovak')
,('Gelateria')
,('Azerbaijani')
,('Juice Bar')
,('Slovenian')
,('Austrian')
,('Georgian')
,('Russian')
,('Organic')
,('Japanese')
,('African')
,('Indian')
,('Donut Shop')
,('Vegan')
,('Mediterranean')
,('Ice Cream Parlor')
,('Brasserie')
,('Sandwich Shop')
,('Czech')
,('Raw')
,('Uzbek')
,('Danish')
,('Seafood')
,('Norwegian')
,('Romanian')
,('Southern')
,('Australian')
,('Persian')
,('Italian')
,('Cuban')
,('Spanish')
,('Afghan')
,('Mongolian')
,('Hungarian')
,('Canadian')
,('Singaporean')
,('Gastropub')
,('Lebanese')
,('Bagel Shop')
,('Chinese')
,('Paleo')
,('Finnish')
,('Argentinian')
,('Fast Food')
,('Polish')
,('Chocolatier')
,('New Zealand')
,('Comfort Food')
,('Nepalese')
,('Creole')
,('Icelandic')
,('Caribbean')
,('Cajun')
,('Turkish')
,('Patisserie')
,('Bangladeshi')
,('Hawaiian')
,('Belgian')
,('Mexican-American')
,('Portuguese')
,('Thai')
,('Vietnamese');
