INSERT INTO ingredients(name,vegetarian,vegan) VALUES
 ('Dry Roasted Peanuts',0,0)
,('Tabasco Sauce',0,0)
,('Goat Cheese',1,1)
,('Ground Cinnamon',0,0)
,('Carrots',1,0)
,('Avocado',1,0)
,('Fresh Dill',1,1)
,('Coconut Milk',1,1)
,('Russet Potatoes',1,0)
,('Cauliflower Florets',0,0)
,('Mozzarella Cheese',1,1)
,('Tomato Paste',0,0)
,('Green Beans',0,0)
,('Sweet Potatoes',1,1)
,('Macaroni',0,0)
,('Canned Black Beans',0,0)
,('Jasmine Rice',0,0)
,('Shallots',1,1)
,('Poblano Peppers',0,0)
,('Soybean Paste',1,0)
,('Curly Kale',0,0)
,('Lime Juice',0,0)
,('Feta Cheese',1,0)
,('Peanut Butter',0,0)
,('Rice Noodles',0,0)
,('Cheddar Cheese',1,1)
,('Ground Turkey',0,0)
,('Aioli',0,0)
,('Egg Noodles',1,0)
,('Shelled Pistachios',0,0)
,('Steak',0,0)
,('Baby Corn',0,0)
,('Cannellini Beans',0,0)
,('Green Cabbage',1,0)
,('Peanuts',0,0)
,('Chicken Drumsticks',1,1)
,('Rutabaga',0,0)
,('Basmati Rice',1,1)
,('Baby Carrots',1,1)
,('Pasta',0,0)
,('Dried Raspberries',1,1)
,('Chia Seed',1,0)
,('Tenderloin',0,0)
,('Japanese Eggplant',0,0)
,('Beef Broth',1,1)
,('Leeks',1,1)
,('Ground Fenugreek',1,1)
,('Tomato',1,0)
,('Scallions',1,0)
,('Canned Cannellini Beans',1,1)
,('Cremini Mushrooms',0,0)
,('Granulated Sugar',1,1)
,('Blanched Almonds',0,0)
,('Split Peas',0,0)
,('Spaghetti',1,0)
,('Fingerling Potatoes',0,0)
,('Jalapeno Peppers',1,1)
,('Cumin',0,0)
,('Whole Wheat Bread',0,0)
,('Fresh Rosemary',1,1)
,('Watercress',1,0)
,('Culantro',1,1)
,('Avocado Oil',1,0)
,('Whole Cloves',0,0)
,('Frozen Mango',0,0)
,('Caraway Seed',1,0)
,('Potatoes',0,0)
,('Celery Seed',0,0)
,('Butter Lettuce',1,1)
,('Vinegar',1,1)
,('Papaya Cubes',0,0)
,('Snow Peas',1,0)
,('Minced Garlic',1,0)
,('Yellow Onion',0,0)
,('Worcestershire Sauce',1,1)
,('Yellow Onions',0,0)
,('Fresh Mint',1,1)
,('Sour Cream',0,0)
,('Parsnips',0,0)
,('Almond Butter',1,0)
,('Chicken Thighs',1,1)
,('White Rice',1,1)
,('Cod',1,0)
,('Canned Kidney Beans',1,0)
,('Raw Almonds',0,0)
,('Chorizo',0,0)
,('Pearl Couscous',0,0);
